on:
  push:
    branches:
    - main
name: Build Package
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn build
    - name: Organize Directory
      run: |
        mkdir ./build
        cp -r ./dist ./build
        cp ./package.json ./build
        cp ./yarn.lock ./build
        echo "This is a built version of the [development branch](https://github.com/danclay/eris-fleet/tree/development). Please visit the development branch for documentation." >> ./build/README.md
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: build
        publish_dir: ./build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        enable_jekyll: true